export const ADD_TO_CART = "ADD_TO_CART";
export const CHANGE_MESSAGE = "CHANGE_MESSAGE";
export const DELETE_PRODUCT_IN_CART = "DELETE_PRODUCT_IN_CART";
export const PLUS_PRODUCT_IN_CART = "PLUS_PRODUCT_IN_CART";
export const MINUS_PRODUCT_IN_CART = "MINUS_PRODUCT_IN_CART";
